import js from "@eslint/js";
import nextPlugin from "@next/eslint-plugin-next";
import reactHooks from "eslint-plugin-react-hooks";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/.next/**",
      "**/node_modules/**",
      "**/.turbo/**",
      "**/coverage/**",
      "apps/web/next-env.d.ts", // generated by Next, not ours to lint
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Root-level CommonJS config files (dependency-cruiser etc.).
    files: ["*.cjs"],
    languageOptions: { globals: globals.node, sourceType: "commonjs" },
  },
  {
    // apps/web only: Next.js core-web-vitals rules + React hooks rules.
    files: ["apps/web/**/*.{ts,tsx}"],
    plugins: { "@next/next": nextPlugin, "react-hooks": reactHooks },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs["core-web-vitals"].rules,
      ...reactHooks.configs.recommended.rules,
      // App Router only — there is no pages/ directory to check links against.
      "@next/next/no-html-link-for-pages": "off",
    },
    settings: { next: { rootDir: "apps/web" } },
  },
);
